# Group Posts

## Posts Collection [/posts]

### Get all Posts [GET]


  + Response 200 (application/json)

    + Attributes (array[Post])

## Post [/posts/{post_id}]

+ Parameters
  + post_id (number) - ID of the Post to be retrieved

### Get a single Post [GET]

  + Response 200 (application/json)
    
    + Attributes (Post)
